/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javanewproject;

import org.apache.commons.math3.stat.descriptive.DescriptiveStatistics;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // Define an array of numbers
        double[] values = {1.2, 2.4, 3.6, 4.8, 6.0};

        // Create a DescriptiveStatistics instance
        DescriptiveStatistics stats = new DescriptiveStatistics();

        // Add the values to the statistics object
        for (double value : values) {
            stats.addValue(value);
        }

        // Calculate the mean and variance
        double mean = stats.getMean();
        double variance = stats.getVariance();

        // Print the results
        System.out.println("Mean = " + mean);
        System.out.println("Variance = " + variance);
    }
}
