server:
  port: 8080

spring:
  application:
    name: housing-service
  config:
    import: optional:file:.env[.properties]
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  # Gmail Setting
  mail:
    host: smtp.gmail.com  # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ${MAIL_USERNAME}  # SMTP 서버 로그인 아이디
    password: ${MAIL_PASSWORD} # SMTP 서버 로그인 비밀번호
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부
          starttls:
            enable: true # starttls 활성화 여부

  # Kakao OAuth2
  security:
    oauth2:
      client:
        registration: # 클라이언트 애플리케이션(Spring Boot)에 대한 설정을 포함합니다.
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post # POST
            scope:
              - ${KAKAO_SCOPE}
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - ${NAVER_SCOPE}
        provider: # OAuth2 인증 제공자에 대한 설정 정보를 포함합니다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


# JWT Secret Key
jwt:
  secret-key: ${JWT_SECRET_KEY}

