server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seyoung5744/spring-cloud-config
#          username: [your username]
#          password: [your password]
#          uri: file:\\\C:\Users\seyou\Desktop\my_Git_Hub\Today-I-Learn\Spring\spring-cloud-config
