server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:\\\C:\Users\seyou\Desktop\my_Git_Hub\Today-I-Learn\Spring\spring-cloud-config
#          default-label: main

