server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native: # C:\Users\seyou\Desktop\my_Git_Hub\Today-I-Learn\Spring\native-config-file
          search-locations: file:///${user.home}/Desktop/my_Git_Hub/Today-I-Learn/Spring/native-config-file
        git:
          uri: https://github.com/seyoung5744/spring-cloud-config
#          username: [your username]
#          password: [your password]
#          uri: file:\\\C:\Users\seyou\Desktop\my_Git_Hub\Today-I-Learn\Spring\spring-cloud-config
